name: Python

on: workflow_dispatch

jobs:
  python1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > python3.8.txt
        
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: python3.8
          path: python3.8.txt

    


